#!/bin/sh

APPDIR=$(readlink -f "$0")
APPDIR=$(dirname "$APPDIR")
java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR:$APPDIR/lib/commons-collections-3.2.1.jar:$APPDIR/lib/el_cuerpo_es_la_llave.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-amd64.jar:$APPDIR/lib/gluegen-rt-natives-linux-amd64.jar:$APPDIR/lib/SimpleOpenNI.jar:$APPDIR/lib/jssc.jar:$APPDIR/lib/serial.jar" el_cuerpo_es_la_llave "$@"
